// 自动生成 (gen_align_order.js): sdenv 实测 264 键顺序 + 11 类 jsdom 真实源码
// 来源: probe_full_sdenv.js → sdenv_winkeys_full.json
// ★ 2026-08-19: 移除前两位 _sdGlobalObject/_globalProxy —
//   sdenv-extend windowGetterUndefinedKeys 显式过滤它们 (ownKeys/has/get 全隐藏),
//   VM 运行期 for-in 无此二键 → nodenv 重建它们 = 每轮 +2 任务 → 指纹分叉 → 400
'use strict';

const SDENV_ORDER = [
 "StyleSheet",
 "MediaList",
 "CSSStyleSheet",
 "CSSRule",
 "CSSStyleRule",
 "CSSMediaRule",
 "CSSImportRule",
 "CSSStyleDeclaration",
 "XPathExpression",
 "XPathResult",
 "XPathEvaluator",
 "onafterprint",
 "onbeforeprint",
 "onbeforeunload",
 "onhashchange",
 "onlanguagechange",
 "onmessage",
 "onmessageerror",
 "onoffline",
 "ononline",
 "onpagehide",
 "onpageshow",
 "onpopstate",
 "onrejectionhandled",
 "onstorage",
 "onunhandledrejection",
 "onunload",
 "onblur",
 "onerror",
 "onfocus",
 "onload",
 "onresize",
 "onscroll",
 "onabort",
 "onauxclick",
 "onbeforeinput",
 "onbeforematch",
 "onbeforetoggle",
 "oncancel",
 "oncanplay",
 "oncanplaythrough",
 "onchange",
 "onclick",
 "onclose",
 "oncontextlost",
 "oncontextmenu",
 "oncontextrestored",
 "oncopy",
 "oncuechange",
 "oncut",
 "ondblclick",
 "ondrag",
 "ondragend",
 "ondragenter",
 "ondragleave",
 "ondragover",
 "ondragstart",
 "ondrop",
 "ondurationchange",
 "onemptied",
 "onended",
 "onformdata",
 "oninput",
 "oninvalid",
 "onkeydown",
 "onkeypress",
 "onkeyup",
 "onloadeddata",
 "onloadedmetadata",
 "onloadstart",
 "onmousedown",
 "onmouseenter",
 "onmouseleave",
 "onmousemove",
 "onmouseout",
 "onmouseover",
 "onmouseup",
 "onpaste",
 "onpause",
 "onplay",
 "onplaying",
 "onprogress",
 "onratechange",
 "onreset",
 "onscrollend",
 "onsecuritypolicyviolation",
 "onseeked",
 "onseeking",
 "onselect",
 "onslotchange",
 "onstalled",
 "onsubmit",
 "onsuspend",
 "ontimeupdate",
 "ontoggle",
 "onvolumechange",
 "onwaiting",
 "onwebkitanimationend",
 "onwebkitanimationiteration",
 "onwebkitanimationstart",
 "onwebkittransitionend",
 "onwheel",
 "ontouchstart",
 "ontouchend",
 "ontouchmove",
 "ontouchcancel",
 "onpointerover",
 "onpointerenter",
 "onpointerdown",
 "onpointermove",
 "onpointerrawupdate",
 "onpointerup",
 "onpointercancel",
 "onpointerout",
 "onpointerleave",
 "ongotpointercapture",
 "onlostpointercapture",
 "_registeredHandlers",
 "_eventHandlers",
 "_resourceLoader",
 "_document",
 "_origin",
 "_sessionHistory",
 "_virtualConsole",
 "_runScripts",
 "_top",
 "_parent",
 "_frameElement",
 "_length",
 "_currentEvent",
 "_pretendToBeVisual",
 "_storageQuota",
 "_commonForOrigin",
 "_currentOriginData",
 "_localStorage",
 "_sessionStorage",
 "_selection",
 "getSelection",
 "_customElementRegistry",
 "name",
 "status",
 "devicePixelRatio",
 "innerWidth",
 "innerHeight",
 "outerWidth",
 "outerHeight",
 "pageXOffset",
 "pageYOffset",
 "screenX",
 "screenLeft",
 "screenY",
 "screenTop",
 "scrollX",
 "scrollY",
 "length",
 "window",
 "frameElement",
 "frames",
 "self",
 "parent",
 "top",
 "document",
 "external",
 "location",
 "history",
 "navigator",
 "locationbar",
 "menubar",
 "personalbar",
 "scrollbars",
 "statusbar",
 "toolbar",
 "performance",
 "screen",
 "crypto",
 "origin",
 "localStorage",
 "sessionStorage",
 "customElements",
 "event",
 "setTimeout",
 "setInterval",
 "clearTimeout",
 "clearInterval",
 "queueMicrotask",
 "requestAnimationFrame",
 "cancelAnimationFrame",
 "postMessage",
 "atob",
 "btoa",
 "stop",
 "close",
 "getComputedStyle",
 "captureEvents",
 "releaseEvents",
 "alert",
 "blur",
 "confirm",
 "focus",
 "moveBy",
 "moveTo",
 "open",
 "print",
 "prompt",
 "resizeBy",
 "resizeTo",
 "scroll",
 "scrollBy",
 "scrollTo",
 "sdenv",
 "closed",
 "opener",
 "clientInformation",
 "isSecureContext",
 "fetch",
 "cancelIdleCallback",
 "createImageBitmap",
 "find",
 "reportError",
 "webkitResolveLocalFileSystemURL",
 "requestIdleCallback",
 "structuredClone",
 "webkitCancelAnimationFrame",
 "webkitRequestAnimationFrame",
 "getScreenDetails",
 "queryLocalFonts",
 "showDirectoryPicker",
 "showOpenFilePicker",
 "showSaveFilePicker",
 "CanvasRenderingContext2D",
 "addEventListener",
 "Navigation",
 "navigation",
 "chrome",
 "VisualViewport",
 "visualViewport",
 "styleMedia",
 "webkitRequestFileSystem",
 "IDBFactory",
 "indexedDB",
 "RTCPeerConnection",
 "MediaQueryList",
 "matchMedia",
 "Request",
 "Worker",
 "$_ts",
 "_$_x",
 "_$mz",
 "_$aR",
 "t",
 "$b_setup",
 "_$ed",
 "_$cV",
 "_$_P",
 "_$cB",
 "_$cb",
 "_$fn",
 "_$ln",
 "_$fx",
 "_$cT",
 "_$$F"
];

const SDENV_CLASS_SRC = {
 "StyleSheet": "function StyleSheet() {\n\tthis.parentStyleSheet = null;\n}",
 "MediaList": "function MediaList(){\n\tthis.length = 0;\n}",
 "CSSStyleSheet": "function CSSStyleSheet() {\n\tCSSOM.StyleSheet.call(this);\n\tthis.cssRules = [];\n}",
 "CSSRule": "function CSSRule() {\n  this.parentRule = null;\n  this.parentStyleSheet = null;\n}",
 "CSSStyleRule": "function CSSStyleRule() {\n\tCSSOM.CSSRule.call(this);\n\tthis.selectorText = \"\";\n\tthis.style = new CSSOM.CSSStyleDeclaration();\n\tthis.style.parentRule = this;\n}",
 "CSSMediaRule": "function CSSMediaRule() {\n\tCSSOM.CSSConditionRule.call(this);\n\tthis.media = new CSSOM.MediaList();\n}",
 "CSSImportRule": "function CSSImportRule() {\n\tCSSOM.CSSRule.call(this);\n\tthis.href = \"\";\n\tthis.media = new CSSOM.MediaList();\n\tthis.styleSheet = new CSSOM.CSSStyleSheet();\n}",
 "CSSStyleDeclaration": "function CSSStyleDeclaration() { [native code] }",
 "XPathExpression": "function XPathExpression(expression, resolver, optDoc) {\n    var stream = new Stream(expression);\n    this._sdAst_210 = parse(stream, astFactory);\n    this._sdDoc_210 = optDoc;\n  }",
 "XPathResult": "function XPathResult(doc, value, resultType) {\n    this._value = value;\n    this._resultType = resultType;\n    this._i = 0;\n\n    // TODO: we removed mutation events but didn't take care of this. No tests fail, so that's nice, but eventually we\n    // should fix this, preferably by entirely replacing our XPath implementation.\n    // this._invalidated = false;\n    // if (this.resultType === XPathResult.UNORDERED_NODE_ITERATOR_TYPE ||\n    //     this.resultType === XPathResult.ORDERED_NODE_ITERATOR_TYPE) {\n    //   doc.addEventListener('DOMSubtreeModified', invalidate, true);\n    //   var self = this;\n    //   function invalidate() {\n    //     self._invalidated = true;\n    //     doc.removeEventListener('DOMSubtreeModified', invalidate, true);\n    //   }\n    // }\n  }",
 "XPathEvaluator": "function XPathEvaluator() {}"
};

const SDENV_TYPES = {
 "_sdGlobalObject": "object",
 "_globalProxy": "object",
 "onafterprint": "object",
 "onbeforeprint": "object",
 "onbeforeunload": "object",
 "onhashchange": "object",
 "onlanguagechange": "object",
 "onmessage": "object",
 "onmessageerror": "object",
 "onoffline": "object",
 "ononline": "object",
 "onpagehide": "object",
 "onpageshow": "object",
 "onpopstate": "object",
 "onrejectionhandled": "object",
 "onstorage": "object",
 "onunhandledrejection": "object",
 "onunload": "object",
 "onblur": "object",
 "onerror": "object",
 "onfocus": "object",
 "onload": "object",
 "onresize": "object",
 "onscroll": "object",
 "onabort": "object",
 "onauxclick": "object",
 "onbeforeinput": "object",
 "onbeforematch": "object",
 "onbeforetoggle": "object",
 "oncancel": "object",
 "oncanplay": "object",
 "oncanplaythrough": "object",
 "onchange": "object",
 "onclick": "object",
 "onclose": "object",
 "oncontextlost": "object",
 "oncontextmenu": "object",
 "oncontextrestored": "object",
 "oncopy": "object",
 "oncuechange": "object",
 "oncut": "object",
 "ondblclick": "object",
 "ondrag": "object",
 "ondragend": "object",
 "ondragenter": "object",
 "ondragleave": "object",
 "ondragover": "object",
 "ondragstart": "object",
 "ondrop": "object",
 "ondurationchange": "object",
 "onemptied": "object",
 "onended": "object",
 "onformdata": "object",
 "oninput": "object",
 "oninvalid": "object",
 "onkeydown": "object",
 "onkeypress": "object",
 "onkeyup": "object",
 "onloadeddata": "object",
 "onloadedmetadata": "object",
 "onloadstart": "object",
 "onmousedown": "object",
 "onmouseenter": "object",
 "onmouseleave": "object",
 "onmousemove": "object",
 "onmouseout": "object",
 "onmouseover": "object",
 "onmouseup": "object",
 "onpaste": "object",
 "onpause": "object",
 "onplay": "object",
 "onplaying": "object",
 "onprogress": "object",
 "onratechange": "object",
 "onreset": "object",
 "onscrollend": "object",
 "onsecuritypolicyviolation": "object",
 "onseeked": "object",
 "onseeking": "object",
 "onselect": "object",
 "onslotchange": "object",
 "onstalled": "object",
 "onsubmit": "object",
 "onsuspend": "object",
 "ontimeupdate": "object",
 "ontoggle": "object",
 "onvolumechange": "object",
 "onwaiting": "object",
 "onwebkitanimationend": "object",
 "onwebkitanimationiteration": "object",
 "onwebkitanimationstart": "object",
 "onwebkittransitionend": "object",
 "onwheel": "object",
 "ontouchstart": "object",
 "ontouchend": "object",
 "ontouchmove": "object",
 "ontouchcancel": "object",
 "onpointerover": "object",
 "onpointerenter": "object",
 "onpointerdown": "object",
 "onpointermove": "object",
 "onpointerrawupdate": "object",
 "onpointerup": "object",
 "onpointercancel": "object",
 "onpointerout": "object",
 "onpointerleave": "object",
 "ongotpointercapture": "object",
 "onlostpointercapture": "object",
 "_registeredHandlers": "object",
 "_eventHandlers": "object",
 "_resourceLoader": "object",
 "_document": "object",
 "_origin": "string",
 "_sessionHistory": "object",
 "_virtualConsole": "object",
 "_runScripts": "undefined",
 "_top": "object",
 "_parent": "object",
 "_frameElement": "object",
 "_length": "number",
 "_currentEvent": "undefined",
 "_pretendToBeVisual": "boolean",
 "_storageQuota": "number",
 "_commonForOrigin": "object",
 "_currentOriginData": "object",
 "_localStorage": "object",
 "_sessionStorage": "object",
 "_selection": "object",
 "_customElementRegistry": "object",
 "name": "string",
 "status": "string",
 "devicePixelRatio": "number",
 "innerWidth": "number",
 "innerHeight": "number",
 "outerWidth": "number",
 "outerHeight": "number",
 "pageXOffset": "number",
 "pageYOffset": "number",
 "screenX": "number",
 "screenLeft": "number",
 "screenY": "number",
 "screenTop": "number",
 "scrollX": "number",
 "scrollY": "number",
 "length": "number",
 "window": "object",
 "frameElement": "object",
 "frames": "object",
 "self": "object",
 "parent": "object",
 "top": "object",
 "document": "object",
 "external": "object",
 "location": "object",
 "history": "object",
 "navigator": "object",
 "locationbar": "object",
 "menubar": "object",
 "personalbar": "object",
 "scrollbars": "object",
 "statusbar": "object",
 "toolbar": "object",
 "performance": "object",
 "screen": "object",
 "crypto": "object",
 "origin": "string",
 "localStorage": "object",
 "sessionStorage": "object",
 "customElements": "object",
 "event": "undefined",
 "sdenv": "object",
 "closed": "boolean",
 "opener": "object",
 "clientInformation": "object",
 "isSecureContext": "boolean",
 "navigation": "object",
 "chrome": "object",
 "visualViewport": "object",
 "styleMedia": "object",
 "indexedDB": "object",
 "$_ts": "object"
};

module.exports = { SDENV_ORDER, SDENV_CLASS_SRC, SDENV_TYPES };
